#!/usr/bin/env bash
#####################################################################
# Author    : Erik Dubois
# Website   : https://kiroproject.be
#####################################################################
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
# Purpose:
#   Generate a colour palette from the current wallpaper with pywal and fan it
#   out to the whole Kiro labwc desktop: waybar (colors.css), mako, AND the
#   Openbox titlebar theme (themerc-override) — then reload each surface.
# Why:
#   The edition's theming engine. labwc has one extra palette surface the other
#   editions don't: the window-decoration themerc, themed separately from the
#   bar — this script keeps both in sync from one wallpaper.
#####################################################################

set -euo pipefail

WALLPAPER="${1:-$HOME/.config/labwc/bg/kiro.jpg}"
CACHE="$HOME/.cache/wal/colors.sh"
WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
MAKO_CONFIG="$HOME/.config/mako/config"
THEMERC="$HOME/.config/labwc/themerc-override"

command -v wal >/dev/null 2>&1 || { echo "pywal (wal) not installed — skipping theme"; exit 0; }
[ -f "$WALLPAPER" ] || { echo "Wallpaper not found: $WALLPAPER"; exit 0; }

wal -i "$WALLPAPER" -n -q
# shellcheck source=/dev/null
source "$CACHE"   # exports $background $foreground $color0 … $color15

# ── waybar ────────────────────────────────────────────────────────────────────
cat > "$WAYBAR_COLORS" <<EOF
/* Generated by set-theme.sh (pywal) from ${WALLPAPER##*/}. */
@define-color bg      ${background};
@define-color fg      ${foreground};
@define-color muted   ${color8};
@define-color accent  ${color4};
@define-color accent2 ${color5};
@define-color info    ${color6};
@define-color good    ${color2};
@define-color warn    ${color3};
@define-color crit    ${color1};
EOF

# ── mako ──────────────────────────────────────────────────────────────────────
if [ -f "$MAKO_CONFIG" ]; then
    sed -i \
        -e "s|^background-color=.*|background-color=${background}|" \
        -e "s|^text-color=.*|text-color=${foreground}|" \
        -e "s|^border-color=.*|border-color=${color4}|" \
        "$MAKO_CONFIG"
fi

# ── labwc titlebar theme (themerc-override) — the labwc-specific surface ──────
cat > "$THEMERC" <<EOF
# Generated by set-theme.sh (pywal) from ${WALLPAPER##*/}.
border.width: 2
window.active.border.color: ${color4}
window.inactive.border.color: ${color8}
window.active.title.bg.color: ${background}
window.inactive.title.bg.color: ${background}
window.active.label.text.color: ${foreground}
window.inactive.label.text.color: ${color8}
window.active.button.unpressed.image.color: ${foreground}
window.inactive.button.unpressed.image.color: ${color8}
menu.border.color: ${color4}
menu.items.bg.color: ${background}
menu.items.text.color: ${foreground}
menu.items.active.bg.color: ${color4}
menu.items.active.text.color: ${background}
menu.title.bg.color: ${color4}
menu.title.text.color: ${background}
osd.bg.color: ${background}
osd.border.color: ${color4}
osd.label.text.color: ${foreground}
EOF

# ── Reload the live surfaces ──────────────────────────────────────────────────
pkill -SIGUSR2 waybar 2>/dev/null || true
makoctl reload 2>/dev/null || true
labwc --reconfigure 2>/dev/null || true   # applies the new themerc live

echo "Theme applied from ${WALLPAPER##*/}"
